# Generated by Django 4.2.5 on 2023-11-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('icon', models.CharField(default='set-iconify-here', max_length=150)),
                ('summary', models.TextField(default='resumen')),
                ('content', models.TextField(default='texto')),
            ],
        ),
        migrations.CreateModel(
            name='Methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=25)),
                ('detail', models.TextField()),
                ('py_snip', models.TextField()),
                ('cpp_snip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('icon', models.CharField(default='set-iconify-here', max_length=150)),
                ('summary', models.TextField(default='resumen')),
                ('content', models.TextField(default='texto')),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('cpp_snippet', models.TextField()),
                ('py_snippet', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.categories')),
            ],
        ),
    ]
