# Generated by Django 4.2.5 on 2023-11-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='summary',
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
