# Generated by Django 4.2.5 on 2023-09-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.ImageField(default='default.png', upload_to='Icons'),
        ),
    ]
