# Generated by Django 4.2.5 on 2023-11-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_remove_types_summary_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Types',
        ),
    ]
