# Generated by Django 4.2.5 on 2023-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_categories_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='icon',
            field=models.CharField(default='set-iconify-here', max_length=150),
        ),
    ]
