# Generated by Django 4.2.5 on 2023-11-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='icon',
        ),
    ]
