# Generated by Django 4.2.5 on 2023-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_remove_types_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='summary',
            field=models.TextField(default='resumen'),
        ),
    ]
