# Generated by Django 4.2.5 on 2023-11-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_types_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='summary',
        ),
    ]
