# Generated by Django 4.2.5 on 2023-11-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_remove_types_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='cppdetails',
            field=models.TextField(default='texto'),
        ),
        migrations.AddField(
            model_name='types',
            name='pydetails',
            field=models.TextField(default='texto'),
        ),
        migrations.AddField(
            model_name='types',
            name='summary',
            field=models.TextField(default='resumen'),
        ),
    ]
