# Generated by Django 4.2.5 on 2023-11-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_types_cppdetails_types_pydetails_types_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='content',
        ),
    ]
