# Generated by Django 4.2.5 on 2023-11-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_remove_types_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='types',
            old_name='cppdetails',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='types',
            name='pydetails',
        ),
        migrations.RemoveField(
            model_name='types',
            name='summary',
        ),
    ]
