# Generated by Django 4.2.5 on 2023-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_rename_cppdetails_types_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
