# Generated by Django 4.2.5 on 2023-11-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_alter_types_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='traduc',
            field=models.CharField(default='traduccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
