# Generated by Django 4.2.5 on 2023-11-08 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_types_traduc_alter_types_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='hasSubcategories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='types',
            name='hasSubtypes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='types',
            name='traduc',
            field=models.CharField(default='traduccion', max_length=25),
        ),
        migrations.CreateModel(
            name='Subtypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('traduc', models.CharField(default='traduccion', max_length=25)),
                ('content', models.TextField(default='texto')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.types')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon', models.CharField(default='set-iconify-here', max_length=150)),
                ('summary', models.TextField(default='resumen')),
                ('content', models.TextField(default='texto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.categories')),
            ],
        ),
    ]
