# Generated by Django 4.2.5 on 2023-11-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_exercises_subcategoty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtypes',
            name='cpp_snippet',
            field=models.TextField(default='texto'),
        ),
        migrations.AddField(
            model_name='subtypes',
            name='py_snippet',
            field=models.TextField(default='texto'),
        ),
    ]
